name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.BONEJ_PLUS_REPO }}"}]'
          githubServer: false
      - name: Set up CI environment
        run: .github/setup.sh
        shell: bash
      - name: Execute the build
        run: .github/build.sh
        shell: bash
        env:
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
          CENTRAL_PASS: ${{ secrets.CENTRAL_PASS }}
          SIGNING_ASC: ${{ secrets.SIGNING_ASC }}
